### ISSUE TITLE
Running on server [multi-user mode]

### ISSUE THREAD

**Issue by chovanecm** [chovanecm/sacredboard#10]
A question to @Qwlouse: Do you think sacredboard could also run on a server, so that one instance would be accessible to multiple users? I can imagine you (or other teams) having one database used by more researchers using one database which could be accessed via one single user interface. It could be useful e.g. where you're on the go and want to check your experiments via mobile or laptop just by visiting something like sacredboard.idsia.ch

This could affect some architectonic decisions, thanks!

**Comment by Qwlouse** [comment]
Absolutely. It would be cool if you could fire up a central instance that can be accessed by many users. But it should also still be possible to start a local sacredboard that can use a local or a remote database.

**Comment by chovanecm** [comment]
Don't worry, that's why also have the other non-functional requirement :-) #9

**Comment by chovanecm** [comment]
Closing for now, as Sacredboard can run on the server, even though all the users see the same.
