### ISSUE TITLE
Filter results by run info

### ISSUE THREAD

**Issue by hamed** [chovanecm/sacredboard#105]
This lovely fronted to sacred only misses one feature that I need (for now :)

In sacred board it is possible to filter the results by config, it would be nice to also filter them based on run info. 
As far as I understood, the configurations are set before the experiment runs, so they can not be updated.
On the other hand, I would like to save some alternative results/intermediate results/updated hyper parameters. I can store them in run info, but then I can not use them to select or sort models.

**Comment by chovanecm** [comment]
Hi,
you can actually filter experiments by almost anything in experiment record (provided that you know the "path" to the information in the model).

Have you noticed the question mark next to the filter input box? It says that you can prefix the query with a leading "." (dot) like in one of the pictures below to query against the "root" of the experiment.

![image](https://user-images.githubusercontent.com/3611258/48063697-224c4c80-e1c6-11e8-8038-8bb67eb1f37f.png)

https://github.com/chovanecm/sacredboard/blob/develop/docs/screenshots.md

**Comment by hamed** [comment]
Thank you very much! You saved my day!
