### ISSUE TITLE
Deleting entries

### ISSUE THREAD

**Issue by chovanecm** [chovanecm/sacredboard#16]
EDIT: Duplicate issue.

From time to time, an experiment run may become useless to be maintained in the database, for instance when it fails and provides no interesting information to the researcher.
Sacredboard shall provide an option to delete the run.

/// for history purposes:
" delete entries (with confirmation and ideally using checkboxes for multiple actions)"

@Qwlouse - Do you mean deleting the whole experiment? (And really deleting it or just marking it as deleted and not showing them, something like a trash bin?) 

An open question (not needed to be answered now)
In "server / multi user mode" (where I expect that you will probably first need to log in somehow), should be this allowed to anyone? (Anyway, as long as you can directly connect to the database from your local machine, you can delete whatever you want, if you decide to. Any logic preventing it in the application wouldn't guarantee it).

**Comment by Qwlouse** [comment]
Good questions. I meant really deleting the entry. But it might be a nice feature to move them to a ``trash`` collection instead. 

And I think authentication is something that we should discuss separately later. For now I think it is fine without, but it is a good feature to keep at the back of our minds.

**Comment by chovanecm** [comment]
From time to time, an experiment run may become useless to be maintained in the database, for instance when it fails and provides no interesting information to the researcher.
Sacredboard shall provide an option to delete the run.

**Comment by chovanecm** [comment]
Closing as duplicate.
