### ISSUE TITLE
More general mongodb connection

### ISSUE THREAD

**Issue by black-puppydog** [chovanecm/sacredboard#21]
If I see correctly, connecting to mongodb at the moment can only be done with a very limited subset of pymongo's capabilities. Would be great if sacredboard's capabilities would match those of sacred itself, so I can use the same config for both :stuck_out_tongue:

**Comment by chovanecm** [comment]
You probably see correctly. Do you mean adding features like authentication? (Currently, a password-protected database is not supported). I am aware of this and I think it should be possible.

Is there anything else than authentication that you are missing?

**Comment by black-puppydog** [comment]
well, at the moment, user/password auth is what I need :)
in the long run, I guess it would be the best to somehow expose all possible configuration options that pymongo supports, that should be possible without doing a lot of "manual" parsing in sacredboard, pymongo already does it quite well, right?

**Comment by chovanecm** [comment]
On the first look, it seems like simply allowing users to specify the connection string manually should work. I'll check it in the next days.
https://docs.mongodb.com/manual/reference/connection-string/

**Comment by chovanecm** [comment]
Could you please try installing the latest development version to check whether it does what you need?
`pip install https://github.com/chovanecm/sacredboard/archive/develop.zip`
You can specify the connection string by using the `-mu mongodb://... DB_NAME` option. It takes two parameters: first is the connection string, second is the name of the Sacred database.

**Comment by black-puppydog** [comment]
Perfect, many thanks! :)
