### ISSUE TITLE
Feature Request: Improved Config display

### ISSUE THREAD

**Issue by Qwlouse** [chovanecm/sacredboard#23]
Here's a wishlist for improving the way the configuration is shown:
- [x] Lists are shown as numbered subentries (e.g. `a=['foo', 'bar']` would become two rows with `a.0   foo` and `a.0   bar`).
- [x] Entries should be sorted alphabetically
- [x] Bonus: It would be cool to group nested subentries (sub-dicts) visually and make them collapsible 
- [x] Bonus: if items are grouped, then sorting such that the groups come first and then the individual entries

The same for "info"

**Comment by chovanecm** [comment]
Hereby I ask for acceptance tests and comments:
(please check out the displayInfo branch)
https://github.com/chovanecm/sacredboard/tree/feature/displayInfo

**Comment by chovanecm** [comment]
If you have an experiment with a lot of config / info entries (including long arrays), please test it as well

**Comment by chovanecm** [comment]
Merged into develop. In case of problems, please reopen the issue.
