### ISSUE TITLE
Support string type id_ values.

### ISSUE THREAD

**Issue by basveeling** [chovanecm/sacredboard#25]
Right now, [get_run()](https://github.com/chovanecm/sacredboard/blob/e2fa62596be89d58333f127f3bc769fa00e1beed/sacredboard/app/data/mongodb.py#L31-L31) requires either an int or ObjectID type for id_. Would you accept a PR that adds support for string type id_ values?

**Comment by chovanecm** [comment]
Hi, sure, I'm open to improvements :) Could you just please specify why need it (does Sacred produce such ids?) Thanks!

**Comment by chovanecm** [comment]
Please develop against the develop branch.

**Comment by basveeling** [comment]
Update: looks like the int `id_` values have been added to sacred only recent, which explains why my team's mongodb contains string `id_`'s. I have to postpone this pr to later this week.

**Comment by chovanecm** [comment]
Hi, is this issue still relevant?

**Comment by basveeling** [comment]
We worked out way around it, thanks for checking!

**Comment by chovanecm** [comment]
Thanks!
