### ISSUE TITLE
How to set the Result column?

### ISSUE THREAD

**Issue by gongbudaizhe** [chovanecm/sacredboard#28]
Hi,

I noticed there is a Result column in sacredboard. How can I set the value for my experiments?

**Comment by chovanecm** [comment]
Hi! 
The result is the value that your experiment main method returns.
For instance,

```python
@ex.automain
def my_main():
    return 42
```
will set the result field of the experiment to 42 :-) I hope this helps.

**Comment by gongbudaizhe** [comment]
Thank you for your prompt reply! 

Great tool by the way : )

**Comment by chovanecm** [comment]
Thanks! :)
