### ISSUE TITLE
A manual refresh button

### ISSUE THREAD

**Issue by Qwlouse** [chovanecm/sacredboard#32]
There should be a button to manually update the table, so that I don't have to uncheck and check a status box. :smile:

**Comment by chovanecm** [comment]
I wanted it to reload automatically e.g. every 5 seconds, but it closes all the opened detail views :(
But adding the button is not a problem.

**Comment by chovanecm** [comment]
Although.. it closes the detail too :/

**Comment by Qwlouse** [comment]
Haha, I guess that'd be fine :wink:
