### ISSUE TITLE
captured output keeps automatically scrolling down to the bottom

### ISSUE THREAD

**Issue by gongbudaizhe** [chovanecm/sacredboard#36]
Hi, 

When viewing captured output, the display panel keeps scrolling down to the bottom, no matter how many times I scroll it up. It is helpful when opening the captured output panel for the first time, since most of the important logging is at the end. But it becomes bothering when looking for more previous logging : (

**Comment by chovanecm** [comment]
Hi,

Thanks for your comment.
The idea was to always show the latest output of the program.
But I agree this might be annoying. I'll try to find a suitable solution soon.

Thanks
Martin

11. 5. 2017 v 14:10, Bi Li <notifications@github.com>:

**Comment by gongbudaizhe** [comment]
I agree that showing the lastest output is helpful when *the program is running*, but less so when it is finished. Looking forward to your solution : )

**Comment by chovanecm** [comment]
You are right, this is really useless for finished experiments. :-)
I'm currently working on release 0.2 (features are done, now I'm polishing the code).
So this could be solved in version 0.2.1 or so that I will try to release asap after 0.2.

**Comment by gongbudaizhe** [comment]
Great! take your time, I am not in a hurry 😃

**Comment by jscheithe** [comment]
Hi @chovanecm, thanks for the great work!
Are there any news on this one?

A quick fix would also be appreciated :)

Thank you!

**Comment by chovanecm** [comment]
Hi, finally got to it. I have added a checkbox that disables or enables scrolling.
I hope to commit the change to the development version today or tomorrow.

![image](https://user-images.githubusercontent.com/3611258/37815906-2fcd31a2-2e71-11e8-9c16-bd593f2462c3.png)

**Comment by jscheithe** [comment]
Thanks!! Much appreciated :)

**Comment by chovanecm** [comment]
Just available in development version 0.4.1.dev0!
The checkbox is automatically disabled/enabled based on whether the experiment is still running or not

Please check it out. You can find instructions for installing the latest development version on the main page.

**Comment by JarnoRFB** [comment]
Hi,
unfortunately it does not work for me in 0.4.1.dev4.

**Comment by chovanecm** [comment]
Hi. Maybe I have to fix some problems with caches. Just to be sure, could you please try clearing the browser cache / using private mode to see if it works? Thank you.

**Comment by JarnoRFB** [comment]
Thanks, it is working now. Most probably was a caching issue.
