### ISSUE TITLE
Carriage returns in the text output

### ISSUE THREAD

**Issue by Henry-E** [chovanecm/sacredboard#39]
I have the [recommended option](http://sacred.readthedocs.io/en/latest/collected_information.html#live-information) implemented to include linefeeds but in sacredboard I still see very verbose logging for progress bars in the captured output.

I'm using tqdm if anyone else has run into this problem before.

**Comment by chovanecm** [comment]
Hi, I believe this may be rather an issue with Sacred.
May I ask you to give me an example of what you expect and what you actually get?
Also, an export of the run from your Mongo database would be helpful. Thanks.

**Comment by Henry-E** [comment]
Thanks for getting back so quick. I will get back to you once i figure out more about the issue and if it's an underlying sacred thing or sacredboard. You might be right that it's a problem with sacred.

**Comment by chovanecm** [comment]
Closing as probably not related to sacredboard itself.
