### ISSUE TITLE
Display host information

### ISSUE THREAD

**Issue by black-puppydog** [chovanecm/sacredboard#45]
Might be useful for others than me, too. E.g. I have my own `host_info_getter` that saves the resources and meta information provided by our cluster system here, but I can't see that info in sacredboard.
Filtering for that info already works fine, but it's a bit weird to filter for things that are not visible...

**Comment by chovanecm** [comment]
Good point, thanks for it.

**Comment by chovanecm** [comment]
Added in development version 0.4.1.dev1.
Sorry for the incredible delay.

Instructions for installing the latest development version can be found on the main page.
