### ISSUE TITLE
quickly find experiment records using experiment id

### ISSUE THREAD

**Issue by gongbudaizhe** [chovanecm/sacredboard#50]
Hi, is there a way to get the experiment records using experiment id?

**Comment by chovanecm** [comment]
Hi, try to use "._id" (without quotes)
út 13. 6. 2017 v 15:34 odesílatel Bi Li <notifications@github.com> napsal:

**Comment by gongbudaizhe** [comment]
Thx 😄

**Comment by chovanecm** [comment]
Not very user friendly, I know :/
