### ISSUE TITLE
[feature request] show repositories information

### ISSUE THREAD

**Issue by gongbudaizhe** [chovanecm/sacredboard#52]
For users who store their repository information(sacred provides a handy utility for this, see [here](http://sacred.readthedocs.io/en/latest/collected_information.html#version-control)) for reproduction, it helps to show informations like: git url, commit hash etc, in sacredboard.

**Comment by gongbudaizhe** [comment]
The lastest develop version already supports this. Ops...

**Comment by chovanecm** [comment]
I like this kind of self-resolving issues! :)
By the way, I just released the current develop as v0.2
