### ISSUE TITLE
Launching TensorBoard 1.2

### ISSUE THREAD

**Issue by chovanecm** [chovanecm/sacredboard#53]
TensorBoard 1.2 outputs something like
`Starting TensorBoard b'54' at http://0.0.0.0:6006` when starting, which is not what Sacredboard expects to detect the port.

**Comment by chovanecm** [comment]
See the [`tensorboard.py`](https://github.com/chovanecm/sacredboard/blob/develop/sacredboard/app/process/tensorboard.py#L49).
Proposal: use the chain of responsibility design pattern to handle all possible cases

**Comment by enricoschroeder** [comment]
Hi there,
any ETA on Tensorboard 1.2/1.3 integration? 
Thanks

**Comment by chovanecm** [comment]
Hi @enricoschroeder. Unfortunately, not. I must admit I haven't worked on Sacredboard much during the summer.
But there is a fork in @hermannsblum's [repository](https://github.com/hermannsblum/sacredboard) that seems to include several patches of the part of the code.
If it works, I'd be happy to include it back to Sacredboard if the authors are willing to contribute it.

**Comment by hermannsblum** [comment]
I myself forked from @LukasMasuch, who fixed the tensorboard issue.
I am using sacredboard for my thesis and therefore working on quite specialized improvements. If there is something more stabel coming out of this I will polish it for a PR. Until then I recommend the patch from [https://github.com/LukasMasuch/sacredboard](https://github.com/LukasMasuch/sacredboard)

**Comment by chovanecm** [comment]
The current dev version fixes the issue of starting Tensorboard. Tested on Linux (Ubuntu). However, tensorboard can be only started once as the port is currently fixed to 6006.
It can be stopped by navigating to /tensorboard/stop

We need a task manager or something in the UI to manage running tensorboards

**Comment by chovanecm** [comment]
Closing, further work is #93 and #92

**Comment by hermannsblum** [comment]
@chovanecm While I still didn't have the time to organize the code properly, I am using a setup where sacredboard and tensorboard are running inside a docker container on any machine you like, and event files are loaded into the tensorboard by selecting them in sacredboard.
I think this would solve a lot of issues, but as I said I will need some time to put it into a proper setup than can be used also by other people.

**Comment by chovanecm** [comment]
@hermannsblum That sounds interesting. I have for now at least managed to get multiple tensorboard instances running at the same time.
