### ISSUE TITLE
how to run sacredboard?

### ISSUE THREAD

**Issue by ahundt** [chovanecm/sacredboard#71]
I was able to install sacredboard with `pip3 install sacredboard` but when I simply run `sacredboard` I get `command not found`. 

Maybe something like the following needs to be done?
https://stackoverflow.com/questions/36092388/adding-installed-pip-package-to-path-automatically

I'm not using virtualenv or anything tricky.

**Comment by chovanecm** [comment]
Hi,
please tell me more about your system. What OS and Python distribution are you using to run Sacredboard on?

On Linux Mint and Arch Linux, where I tried it, the installer created a startup script for sacredboard in `/usr/bin`, which is normally on path. Of course, I had to run `pip` (or `pip3`) as root when not in a virtualenv.

Similar for the [Anaconda Python distribution](https://docs.continuum.io/anaconda/install/windows) that I'm using on Windows.
Thank you for letting me know about your system.

**Comment by ahundt** [comment]
I'm on OS X but interestingly I uninstalled and reinstalled and it seems to show up now. I'll try it out now. Sorry for the trouble!
