### ISSUE TITLE
Filtering on experiments

### ISSUE THREAD

**Issue by chovanecm** [chovanecm/sacredboard#8]
As a user, I want to show only experiments that match (or don't match) certain criteria, such as:
- [x] machine where an experiment runs on
- [x] experiment name
- [x] experiment state
- [x] the result field of an experiment
- [ ] the last / minimal / maximal value of certain metric (such as accuracy) is bigger / lower than...
- [x] arbitrary value in arbitrary field stored even somewhere deep in the record structure
- [x] users shouldn't be forced to write "config.something" everytime, instead: write simply "seed" for searching in "config.seed" or ".host.hostname" for "host.hostname".

Precondition: Sacredboard is running and the user sees the experiment run list

### Base Course of Events
1. The user indicates that the software is to perform filtering of the run list.
2. The software responds by requesting the name of the experiment config property to be filtered on, the comparison operator and the searched value.
3. The user inputs the configuration property name and the comparison operator and indicates the type of the searched value (number/string/date).
4. The software applies the selected filter additionally to other filters that have been possibly applied before and indicates that a new filter condition has been added.

### Alternative Paths
1. In Step 3 the user indicates he does not wish to perform the search based on an experiment run configuration property but based on another property of the experiment (not necessarily in the run `config` section). The software will allow that.
In Step 1, the user indicates that he wants to instantly filter out experiments that have a certain state (e.g. FINISHED and INTERRUPTED). The software must support it without requesting any details about property names.
3.  In Step 3, the user indicates he wants to filter based on an invalid combination of operator and value (e.g. number and "contains"). In this case, the software indicates that the choice is invalid and prevents the user from continuing to the next step.
4. In Step 1, the user indicates he wants to remove one of the existing filters instead. The software removes the filter of user's choice. All the postconditions apply.

### Postconditions
1. The run list displays only results matching criteria of all the filters applied so far.
2. The software indicates all the filters applied.

**Comment by chovanecm** [comment]
@Qwlouse, can you please help me specifying what do you expect from the filters?

**Comment by Qwlouse** [comment]
This first draft looks ok to me. Some filtering based on the configuration would probably also be nice. But I'll think more about it and discuss it with my colleagues.

**Comment by chovanecm** [comment]
Precondition: Sacredboard is running and the user sees the experiment run list

### Base Course of Events
1. The user indicates that the software is to perform filtering of the run list.
2. The software responds by requesting the name of the experiment run property to be filtered on, the comparison operator and the searched value.
3. The user inputs the configuration property name and the comparison operator and indicates the type of the searched value (number/string/date).
4. The software applies the selected filter additionally to other filters that have been possibly applied before and indicates that a new filter condition has been added.

### Alternative Paths
1. In Step 3 the user indicates he does not wish to perform the search based on an experiment run configuration property but based on another property of the experiment (not necessarily in the run `config` section). The software will allow that.
2.  In Step 3, the user indicates he wants to filter based on an invalid combination of operator and value (e.g. number and "contains"). In this case, the software indicates that the choice is invalid and prevents the user from continuing to the next step.
3. In Step 1, the user indicates he wants to remove one of the existing filters instead. The software removes the filter of user's choice. All the postconditions apply.

### Postconditions
1. The run list displays only results matching criteria of all the filters applied so far.
2. The software indicates all the filters applied.

**Comment by chovanecm** [comment]
Closing, additional features are in #34 and #35.
