### ISSUE TITLE
Viewing source saved

### ISSUE THREAD

**Issue by evolu8** [chovanecm/sacredboard#91]
How do I view the source saved:

![image](https://user-images.githubusercontent.com/1828165/39533553-40c64914-4e27-11e8-855d-f05c65309110.png)

**Comment by chovanecm** [comment]
There is currently no other way than to directly connect to MongoDB and fetch the file on your own, sorry. :(

**Comment by evolu8** [comment]
OK , then this would be a feature request I guess.

**Comment by verybadsoldier** [comment]
Yes, this would be really handy.

**Comment by chovanecm** [comment]
Available in the latest development version thanks to @verybadsoldier
