### ISSUE TITLE
metrics plots: Tick all metrics by default

### ISSUE THREAD

**Issue by Avsecz** [chovanecm/sacredboard#95]
Currently, in the 'Metrics plots' none of the metrics are selected by default. I think it would be faster for the if all the metrics were selected/displayed by default.

**Comment by Gonzalo933** [comment]
What if the metrics are in really different scales? some of the metrics with just look like straight lines. Sometimes it makes no sense to plot all the metrics at the same time

**Comment by chovanecm** [comment]
I can add additional checkbox "select all" so that the user could select all metrics in one click. What do you think?

**Comment by chovanecm** [comment]
Available in the latest dev version (0.4.1.dev5)
