### ISSUE TITLE
Show comment in the overview table

### ISSUE THREAD

**Issue by Avsecz** [chovanecm/sacredboard#96]
I think that in addition to displaying the command name in the overview table, it would be useful to display the comment from the meta-info section. For easier display, the comment could be truncated to only say 40 characters

**Comment by chovanecm** [comment]
Sounds like another argument for #24

**Comment by Avsecz** [comment]
yup. I can close it as a duplicate.

**Comment by Avsecz** [comment]
duplicate of https://github.com/chovanecm/sacredboard/issues/24
